export type TagVariant =
  | "three"
  | "websockets"
  | "react"
  | "redis"
  | "gray"
  | "html"
  | "css"
  | "javascript"
  | "node"
  | "next"
  | "kubernetes"
  | "postgresql"
  | "ogl"
  | "glsl"
  | "typescript"
  | "pokeapi"
  | "python"
  | "n8n"
  | "rag"
  | "langgraph"
  | "docker"
  | "openrouter"
  | "wordpress"
  | "prestashop"
  | "shopify"
  | "php"
  | "seo"
  | "api"
  | "godot"
  | "aseprite"
  | "gimp"
  | "pixelart"
  | "gdscript";

export const tagLabels = {
  three: "Three.js",
  websockets: "WebSockets",
  react: "React",
  redis: "Redis",
  gray: "Gray",
  html: "HTML",
  css: "CSS",
  javascript: "JavaScript",
  node: "Node.js",
  next: "Next.js",
  kubernetes: "Kubernetes",
  postgresql: "PostgreSQL",
  ogl: "OGL.js",
  glsl: "GLSL",
  typescript: "TypeScript",
  pokeapi: "PokéAPI",
  python: "Python",
  n8n: "n8n",
  rag: "RAG",
  langgraph: "LangGraph",
  docker: "Docker",
  openrouter: "OpenRouter",
  wordpress: "WordPress",
  prestashop: "PrestaShop",
  shopify: "Shopify",
  php: "PHP",
  seo: "SEO",
  api: "API",
  godot: "Godot",
  aseprite: "Aseprite",
  gimp: "GIMP",
  pixelart: "Pixel Art",
  gdscript: "GDScript",
} as const satisfies Record<TagVariant, string>;
